import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)


_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = 'gray40' # X11 color: #666666
_ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
_ana2color = 'beige' # X11 color: #f5f5dc
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_tabbg1 = 'grey75' 
_tabbg2 = 'grey89' 
_bgmode = 'light' 

_style_code_ran = 0

def _style_code():
       global _style_code_ran
       if _style_code_ran:
           return
       style = ttk.Style()
       if sys.platform == "win32":
           style.theme_use('winnative')
           style.configure('.',background=_bgcolor)
           style.configure('.',foreground=_fgcolor)
           style.configure('.',font='TkDefaultFont')
           style.map('.',background = [('selected', _compcolor), ('active',_ana2color)])
           if _bgmode == 'dark':
              style.map('.',foreground = [('selected', 'white'), ('active','white')])
           else:
            style.map('.',foreground = [('selected', 'black'), ('active','black')]) 
            style.map('TRadiobutton',background =[('selected', _bgcolor), ('active', _ana2color)], indicatorcolor = [('selected', _fgcolor), ('!active', _bgcolor)]) 
           _style_code_ran = 1


class Cadastro:
    def __init__(self, root=None):
        
        self.root = tk.Tk()
        self.root.resizable( True,True)
        self.root.geometry("692x464+246+234")
        self.root.minsize(120, 1)
        self.root.maxsize(1924, 1061)
        self.root.resizable(1,  1)
        self.root.title("Realizar/ Atualiar cadastro")
        self.root.configure(background="#000000")
        self.root.configure(highlightbackground="#d9d9d9")
        self.root.configure(highlightcolor="black")

        self.root = self.root

        self.Frame1 = tk.Frame(self.root)
        self.Frame1.place(relx=0.014, rely=0.022, relheight=0.938 , relwidth=0.974)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")

        self.nome = tk.Label(self.Frame1)
        self.nome.place(relx=0.015, rely=0.126, height=31, width=64)
        self.nome.configure(anchor='w')
        self.nome.configure(background="#d9d9d9")
        self.nome.configure(compound='left')
        self.nome.configure(cursor="fleur")
        self.nome.configure(disabledforeground="#a3a3a3")
        self.nome.configure(foreground="#000000")
        self.nome.configure(text='''Nome:''')

        self.endereco = tk.Label(self.Frame1)
        self.endereco.place(relx=0.015, rely=0.218, height=31, width=64)
        self.endereco.configure(activebackground="#f9f9f9")
        self.endereco.configure(anchor='w')
        self.endereco.configure(background="#d9d9d9")
        self.endereco.configure(compound='left')
        self.endereco.configure(cursor="fleur")
        self.endereco.configure(disabledforeground="#a3a3a3")
        self.endereco.configure(foreground="#000000")
        self.endereco.configure(highlightbackground="#d9d9d9")
        self.endereco.configure(highlightcolor="black")
        self.endereco.configure(text='''Endereço:''')

        self.Entry_nome = tk.Entry(self.Frame1)
        self.Entry_nome.place(relx=0.089, rely=0.138, height=20, relwidth=0.51)
        self.Entry_nome.configure(background="white")
        self.Entry_nome.configure(disabledforeground="#a3a3a3")
        self.Entry_nome.configure(font="TkFixedFont")
        self.Entry_nome.configure(foreground="#000000")
        self.Entry_nome.configure(insertbackground="black")

        self.Entry_endereco = tk.Entry(self.Frame1)
        self.Entry_endereco.place(relx=0.104, rely=0.23, height=20, relwidth=0.51)
        self.Entry_endereco.configure(background="white")
        self.Entry_endereco.configure(disabledforeground="#a3a3a3")
        self.Entry_endereco.configure(font="TkFixedFont")
        self.Entry_endereco.configure(foreground="#000000")
        self.Entry_endereco.configure(highlightbackground="#d9d9d9")
        self.Entry_endereco.configure(highlightcolor="black")
        self.Entry_endereco.configure(insertbackground="black")
        self.Entry_endereco.configure(selectbackground="#c4c4c4")
        self.Entry_endereco.configure(selectforeground="black")

        self.titulo_cadastro = tk.Label(self.Frame1)
        self.titulo_cadastro.place(relx=0.310, rely=0.023, height=22, width=300)
        self.titulo_cadastro.configure(anchor='w')
        self.titulo_cadastro.configure(background="#d9d9d9")
        self.titulo_cadastro.configure(compound='left')
        self.titulo_cadastro.configure(disabledforeground="#a3a3a3")
        self.titulo_cadastro.configure(font="-family {Georgia} -size 20 -weight bold -slant italic")
        self.titulo_cadastro.configure(foreground="#000000")
        self.titulo_cadastro.configure(text='''Cadastro De Clientes''')

        self.email = tk.Label(self.Frame1)
        self.email.place(relx=0.015, rely=0.448, height=31, width=64)
        self.email.configure(activebackground="#f9f9f9")
        self.email.configure(anchor='w')
        self.email.configure(background="#d9d9d9")
        self.email.configure(compound='left')
        self.email.configure(disabledforeground="#a3a3a3")
        self.email.configure(foreground="#000000")
        self.email.configure(highlightbackground="#d9d9d9")
        self.email.configure(highlightcolor="black")
        self.email.configure(text='''Email:''')

        self.Entry_email = tk.Entry(self.Frame1)
        self.Entry_email.place(relx=0.074, rely=0.46, height=20, relwidth=0.525)
        self.Entry_email.configure(background="white")
        self.Entry_email.configure(disabledforeground="#a3a3a3")
        self.Entry_email.configure(foreground="#000000")
        self.Entry_email.configure(highlightbackground="#d9d9d9")
        self.Entry_email.configure(highlightcolor="black")
        self.Entry_email.configure(insertbackground="black")
        self.Entry_email.configure(selectbackground="#c4c4c4")
        self.Entry_email.configure(selectforeground="black")
  


        self.cpf = tk.Label(self.Frame1)
        self.cpf.place(relx=0.638, rely=0.126, height=31, width=64)
        self.cpf.configure(activebackground="#f9f9f9")
        self.cpf.configure(anchor='w')
        self.cpf.configure(background="#d9d9d9")
        self.cpf.configure(compound='left')
        self.cpf.configure(disabledforeground="#a3a3a3")
        self.cpf.configure(foreground="#000000")
        self.cpf.configure(highlightbackground="#d9d9d9")
        self.cpf.configure(highlightcolor="black")
        self.cpf.configure(text='''Cpf:''')

        self.Entry_cpf = tk.Entry(self.Frame1)
        self.Entry_cpf.place(relx=0.697, rely=0.138, height=20, relwidth=0.258)
        self.Entry_cpf.configure(background="white")
        self.Entry_cpf.configure(disabledforeground="#a3a3a3")
        self.Entry_cpf.configure(font="TkFixedFont")
        self.Entry_cpf.configure(foreground="#000000")
        self.Entry_cpf.configure(highlightbackground="#d9d9d9")
        self.Entry_cpf.configure(highlightcolor="black")
        self.Entry_cpf.configure(insertbackground="black")
        self.Entry_cpf.configure(selectbackground="#c4c4c4")
        self.Entry_cpf.configure(selectforeground="black")

        self.teelefone = tk.Label(self.Frame1)
        self.teelefone.place(relx=0.638, rely=0.448, height=31, width=64)
        self.teelefone.configure(activebackground="#f9f9f9")
        self.teelefone.configure(anchor='w')
        self.teelefone.configure(background="#d9d9d9")
        self.teelefone.configure(compound='left')
        self.teelefone.configure(disabledforeground="#a3a3a3")
        self.teelefone.configure(foreground="#000000")
        self.teelefone.configure(highlightbackground="#d9d9d9")
        self.teelefone.configure(highlightcolor="black")
        self.teelefone.configure(text='''Telefone:''')
  

        self.Entry_telefone = tk.Entry(self.Frame1)
        self.Entry_telefone.place(relx=0.727, rely=0.46, height=20, relwidth=0.228)
        self.Entry_telefone.configure(background="white")
        self.Entry_telefone.configure(disabledforeground="#a3a3a3")
        self.Entry_telefone.configure(font="TkFixedFont")
        self.Entry_telefone.configure(foreground="#000000")
        self.Entry_telefone.configure(highlightbackground="#d9d9d9")
        self.Entry_telefone.configure(highlightcolor="black")
        self.Entry_telefone.configure(insertbackground="black")
        self.Entry_telefone.configure(selectbackground="#c4c4c4")
        self.Entry_telefone.configure(selectforeground="black")

        self.CEP = tk.Label(self.Frame1)
        self.CEP.place(relx=0.653, rely=0.218, height=31, width=64)
        self.CEP.configure(activebackground="#f9f9f9")
        self.CEP.configure(anchor='w')
        self.CEP.configure(background="#d9d9d9")
        self.CEP.configure(compound='left')
        self.CEP.configure(disabledforeground="#a3a3a3")
        self.CEP.configure(foreground="#000000")
        self.CEP.configure(highlightbackground="#d9d9d9")
        self.CEP.configure(highlightcolor="black")
        self.CEP.configure(text='''CEP:''')

        self.Entry_cep = tk.Entry(self.Frame1)
        self.Entry_cep.place(relx=0.697, rely=0.23, height=20, relwidth=0.258)
        self.Entry_cep.configure(background="white")
        self.Entry_cep.configure(disabledforeground="#a3a3a3")
        self.Entry_cep.configure(font="TkFixedFont")
        self.Entry_cep.configure(foreground="#000000")
        self.Entry_cep.configure(highlightbackground="#d9d9d9")
        self.Entry_cep.configure(highlightcolor="black")
        self.Entry_cep.configure(insertbackground="black")
        self.Entry_cep.configure(selectbackground="#c4c4c4")
        self.Entry_cep.configure(selectforeground="black")

        self.Estado = tk.Label(self.Frame1)
        self.Estado.place(relx=0.015, rely=0.379, height=31, width=64)
        self.Estado.configure(activebackground="#f9f9f9")
        self.Estado.configure(anchor='w')
        self.Estado.configure(background="#d9d9d9")
        self.Estado.configure(compound='left')
        self.Estado.configure(cursor="fleur")
        self.Estado.configure(disabledforeground="#a3a3a3")
        self.Estado.configure(foreground="#000000")
        self.Estado.configure(highlightbackground="#d9d9d9")
        self.Estado.configure(highlightcolor="black")
        self.Estado.configure(text='''Estado:''')

        self.Entry_estado = tk.Entry(self.Frame1)
        self.Entry_estado.place(relx=0.089, rely=0.391, height=20, relwidth=0.228)
        self.Entry_estado.configure(background="white")
        self.Entry_estado.configure(disabledforeground="#a3a3a3")
        self.Entry_estado.configure(font="TkFixedFont")
        self.Entry_estado.configure(foreground="#000000")
        self.Entry_estado.configure(highlightbackground="#d9d9d9")
        self.Entry_estado.configure(highlightcolor="black")
        self.Entry_estado.configure(insertbackground="black")
        self.Entry_estado.configure(selectbackground="#c4c4c4")
        self.Entry_estado.configure(selectforeground="black")

        self.Cidade = tk.Label(self.Frame1)
        self.Cidade.place(relx=0.341, rely=0.379, height=31, width=64)
        self.Cidade.configure(activebackground="#f9f9f9")
        self.Cidade.configure(anchor='w')
        self.Cidade.configure(background="#d9d9d9")
        self.Cidade.configure(compound='left')
        self.Cidade.configure(disabledforeground="#a3a3a3")
        self.Cidade.configure(foreground="#000000")
        self.Cidade.configure(highlightbackground="#d9d9d9")
        self.Cidade.configure(highlightcolor="black")
        self.Cidade.configure(text='''Cidade:''')

        self.Entry_cidade = tk.Entry(self.Frame1)
        self.Entry_cidade.place(relx=0.415, rely=0.391, height=20, relwidth=0.214)
        self.Entry_cidade.configure(background="white")
        self.Entry_cidade.configure(disabledforeground="#a3a3a3")
        self.Entry_cidade.configure(font="TkFixedFont")
        self.Entry_cidade.configure(foreground="#000000")
        self.Entry_cidade.configure(highlightbackground="#d9d9d9")
        self.Entry_cidade.configure(highlightcolor="black")
        self.Entry_cidade.configure(insertbackground="black")
        self.Entry_cidade.configure(selectbackground="#c4c4c4")
        self.Entry_cidade.configure(selectforeground="black")

        self.Bairro = tk.Label(self.Frame1)
        self.Bairro.place(relx=0.653, rely=0.379, height=31, width=64)
        self.Bairro.configure(activebackground="#f9f9f9")
        self.Bairro.configure(anchor='w')
        self.Bairro.configure(background="#d9d9d9")
        self.Bairro.configure(compound='left')
        self.Bairro.configure(disabledforeground="#a3a3a3")
        self.Bairro.configure(foreground="#000000")
        self.Bairro.configure(highlightbackground="#d9d9d9")
        self.Bairro.configure(highlightcolor="black")
        self.Bairro.configure(text='''Bairro:''')

        self.Entry_bairro = tk.Entry(self.Frame1)
        self.Entry_bairro.place(relx=0.727, rely=0.391, height=20, relwidth=0.228)
        self.Entry_bairro.configure(background="white")
        self.Entry_bairro.configure(disabledforeground="#a3a3a3")
        self.Entry_bairro.configure(font="TkFixedFont")
        self.Entry_bairro.configure(foreground="#000000")
        self.Entry_bairro.configure(highlightbackground="#d9d9d9")
        self.Entry_bairro.configure(highlightcolor="black")
        self.Entry_bairro.configure(insertbackground="black")
        self.Entry_bairro.configure(selectbackground="#c4c4c4")
        self.Entry_bairro.configure(selectforeground="black")
        

        self.Confirmar_cadastro = tk.Button(self.Frame1)
        self.Confirmar_cadastro.place(relx=0.49, rely=0.69, height=34, width=157)
        self.Confirmar_cadastro.configure(activebackground="beige")
        self.Confirmar_cadastro.configure(activeforeground="black")
        self.Confirmar_cadastro.configure(background="#008000")
        self.Confirmar_cadastro.configure(compound='left')
        self.Confirmar_cadastro.configure(disabledforeground="#a3a3a3")
        self.Confirmar_cadastro.configure(foreground="#ffffff")
        self.Confirmar_cadastro.configure(highlightbackground="#d9d9d9")
        self.Confirmar_cadastro.configure(highlightcolor="black")
        self.Confirmar_cadastro.configure(pady="0")
        self.Confirmar_cadastro.configure(text='''Atualizar / Cadastrar''')

       
        self.excluir_cadastro = tk.Button(self.Frame1)
        self.excluir_cadastro.place(relx=0.208, rely=0.69, height=34, width=157)
        self.excluir_cadastro.configure(activebackground="beige")
        self.excluir_cadastro.configure(activeforeground="black")
        self.excluir_cadastro.configure(background="#ff0000")
        self.excluir_cadastro.configure(compound='left')
        self.excluir_cadastro.configure(disabledforeground="#a3a3a3")
        self.excluir_cadastro.configure(foreground="#ffffff")
        self.excluir_cadastro.configure(highlightbackground="#d9d9d9")
        self.excluir_cadastro.configure(highlightcolor="black")
        self.excluir_cadastro.configure(pady="0")
        self.excluir_cadastro.configure(text='''Excluir Cadastro''')

        _style_code()

        self.TSeparator1 = ttk.Separator(self.Frame1)
        self.TSeparator1.place(relx=0.463, rely=0.692,  relheight=0.078)
        self.TSeparator1.configure(orient="vertical")

        self.seletor_sexo = tk.Label(self.Frame1)
        self.seletor_sexo.place(relx=0.015, rely=0.299, height=31, width=64)
        self.seletor_sexo.configure(activebackground="#f9f9f9")
        self.seletor_sexo.configure(anchor='w')
        self.seletor_sexo.configure(background="#d9d9d9")
        self.seletor_sexo.configure(compound='left')
        self.seletor_sexo.configure(disabledforeground="#a3a3a3")
        self.seletor_sexo.configure(foreground="#000000")
        self.seletor_sexo.configure(highlightbackground="#d9d9d9")
        self.seletor_sexo.configure(highlightcolor="black")
        self.seletor_sexo.configure(text='''Sexo:''')

        self.seletor_sexo_masculino = ttk.Radiobutton(self.Frame1)
        self.seletor_sexo_masculino.place(relx=0.104, rely=0.31, relwidth=0.117, relheight=0.0, height=21) 
        self.seletor_sexo_masculino.configure(variable=self.seletor_sexo_masculino)
        self.seletor_sexo_masculino.configure(text='''Masculino''')
        self.seletor_sexo_masculino.configure(compound='left')

        self.seletor_sexo_feminino = ttk.Radiobutton(self.Frame1)
        self.seletor_sexo_feminino.place(relx=0.223, rely=0.31, relwidth=0.117, relheight=0.0, height=21)
        self.seletor_sexo_feminino.configure(variable=self.seletor_sexo_feminino)
        self.seletor_sexo_feminino.configure(text='''Feminino''')
        self.seletor_sexo_feminino.configure(compound='left')

        self.data_de_nascimento = tk.Label(self.Frame1)
        self.data_de_nascimento.place(relx=0.341, rely=0.299, height=31, width=124)
        self.data_de_nascimento.configure(activebackground="#f9f9f9")
        self.data_de_nascimento.configure(anchor='w')
        self.data_de_nascimento.configure(background="#d9d9d9")
        self.data_de_nascimento.configure(compound='left')
        self.data_de_nascimento.configure(disabledforeground="#a3a3a3")
        self.data_de_nascimento.configure(foreground="#000000")
        self.data_de_nascimento.configure(highlightbackground="#d9d9d9")
        self.data_de_nascimento.configure(highlightcolor="black")
        self.data_de_nascimento.configure(text='''Data de Nascimento:''')

        self.Entry_datanascimento = tk.Entry(self.Frame1)
        self.Entry_datanascimento.place(relx=0.519, rely=0.31, height=20 , relwidth=0.243)
        self.Entry_datanascimento.configure(background="white")
        self.Entry_datanascimento.configure(disabledforeground="#a3a3a3")
        self.Entry_datanascimento.configure(font="TkFixedFont")
        self.Entry_datanascimento.configure(foreground="#000000")
        self.Entry_datanascimento.configure(highlightbackground="#d9d9d9")
        self.Entry_datanascimento.configure(highlightcolor="black")
        self.Entry_datanascimento.configure(insertbackground="black")
        self.Entry_datanascimento.configure(selectbackground="#c4c4c4")
        self.Entry_datanascimento.configure(selectforeground="black")

        self.root.mainloop()

Cadastro()
